version: '3.4'
services:
  app:
    build:
      context: .
      target: build
    command: yarn watch
    depends_on:
      - postgres
    environment:
      - NODE_ENV=development
      - NODE_CONFIG_ENV=development
    networks:
      - default
    ports:
      - '4000:4000'
    volumes:
      - '.:/code'
      - /code/node_modules
  postgres:
    image: 'postgres:9.6-alpine'
    environment:
      POSTGRES_DB: test
      POSTGRES_PASSWORD: pass
      POSTGRES_USER: user
    networks:
      - default
    volumes:
      - 'postgres:/var/lib/postgresql/data'
networks:
  default: {}
volumes:
  postgres: {}
